name: From testing to build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  format-check-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r dev-requirements.txt

      - name: Run Black
        run: black --check .

      - name: Run pytest
        run: PYTHONPATH=$(pwd) pytest

  docker-build-and-push:
    needs: format-check-and-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA
          docker push ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA